FROM oven/bun:1

WORKDIR /usr/src/apps

ARG DATABASE_URL

COPY ./packages ./packages

COPY ./bun.lock ./bun.lock

COPY ./turbo.json ./turbo.json

COPY ./package.josn ./package.json

COPY ./apps/web ./apps/web

RUN bun install

COPY . .

RUN bun install
RUN bun run db:generate
RUN DATABASE_URL=${DATABASE_URL} bun run build

EXPOSE 3000

CMD [ "bun","run","start:web" ]